### ISSUE TITLE
"useRuntimeConfig is not defined" after upgrading to v5.2.0

### ISSUE THREAD

**Issue by matt-clegg** [Intevel/nuxt-directus#140]
### Version

nuxt-directus v5.2.0
nuxt: v3.4.2

### Steps to reproduce

I was previously running v5.1.3, I just upgraded to v5.2.0 and now my nuxt app is no longer working and is throwing an error on startup. 

### What is actually happening?

The following error is thrown on the server:
```
[nuxt] [request error] [unhandled] [500] useRuntimeConfig is not defined
   at Module.useDirectusToken (./node_modules/nuxt-directus/dist/runtime/composables/useDirectusToken.mjs:8:34)  
   at Module.useDirectus (./node_modules/nuxt-directus/dist/runtime/composables/useDirectus.mjs:10:43)  
   at Module.useDirectusAuth (./node_modules/nuxt-directus/dist/runtime/composables/useDirectusAuth.mjs:11:42)  
   at Object.setup (./node_modules/nuxt-directus/dist/runtime/plugin.mjs:10:49)  
   at wrapper (./node_modules/nuxt/dist/app/nuxt.js:198:21)  
   at fn (./node_modules/nuxt/dist/app/nuxt.js:214:27)  
   at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:55)  
   at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.js:216:23)  
   at applyPlugin (./node_modules/nuxt/dist/app/nuxt.js:129:29)  
   at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.js:139:11)
```

and in the browser:
![image](https://user-images.githubusercontent.com/34515355/234775224-eec184da-d143-4cc6-b721-9057ceb57949.png)

**Comment by NeekoDev** [comment]
I can confirm this bug too.

`nuxt-directus : 5.2.0`
`directus : 9.26.0`

**Comment by casualmatt** [comment]
I'm checking

**Comment by casualmatt** [comment]
The bug is present just when the module is built, not in the playground, and now I understand why we didn't see it.
